### PR TITLE
k-RR mechanism

### PR DESCRIPTION
**Pull request by ramongonze**
Implementation of k-RR mechanism, a special case of staircase mechanisms, when X = Y.
The implementation takes just the epsilon parameter and the domain values.

### CODE REVIEW

**Comment by naoise-h** [comment]
Dear Ramon, thanks for your interest in diffprivlib and for issuing the PR.

For the task that you are implementing, this functionality is already present in the `ExponentialHierarchical` mechanism. After a quick look at your syntax, if you wish to initialise with `KRR(epsilon=1, domain_values=["val1", "val2", "val3"])`, you can use `ExponentialHierarchical(epsilon=1, hierarchy=["val1", "val2", "val3"])` to achieve the same.

**Comment by ramongonze** [comment]
Oh, I did not notice it was the same mechanism. Is it possible to expand ExponentialHierarchical to accept other values than only str? I'm asking that because we can represent strings as integers in a dataset (keeping the domain categorical) to make an algorithm faster.

**Comment by naoise-h** [comment]
So, as it's currently implemented, the domain values need to be strings. However, you can use a mechanism transform to work around this.

As an example, if you want to use `[1, 2, 3]` as your domain values, you can use the `IntToString` transform to handle the correct casting of the input and output as follows:
`mech = transforms.IntToString(ExponentialHierarchical(epsilon=1, hierarchy=["1", "2", "3"]))`. Then, doing `mech.randomise(1)` (an integer input) will give an integer output, like `2`.

**Comment by ramongonze** [comment]
Thank you so much!

**Pull request closed without merging**
